export const GEs = {
  'L&S': ['A1', 'A2', 'B', 'C', 'D', 'E', 'F', 'G', 'EUR', 'ETH', 'NWC', 'QNT', 'WRT'],
  'ENGR': ['A1', 'A2', 'D', 'E', 'E1', 'F', 'G', 'H', 'EUR', 'ETH', 'NWC', 'WRT'],
  'CRST': ['B', 'C', 'E1', 'ETH'],
  'UCSB': ['AMH', 'SUB']
}

export const departments = {
  'ANTH': 'Anthropology',
  'ARTHI': 'Hist of Art&Arc',
  'ASAM': 'Asian Amer Stds',
  'BLKST': 'Black Studies',
  'CHEM': 'Chem & Biochem',
  'CHST': 'Chicano Studies',
  'CLIT': 'Comparative Lit',
  'CMPSC': 'Computer Sci',
  'CNENG': 'Chemical Engr',
  'CRSTU': 'Creative Stds',
  'DA': 'Dramatic Art',
  'ECE': 'Elect Comp Engr',
  'ECON': 'Economics',
  'EDUC': 'Education',
  'ENGL': 'English',
  'ENGSC': 'Engineering Sci',
  'ENVST': 'Environ Studies',
  'FLMST': 'Film & Media St',
  'FR&IT': 'French & Ital',
  'GEOG': 'Geography',
  'GERSL': 'German & Slavic',
  'HIST': 'History',
  'INT': 'Interdisciplin',
  'L&S': 'Letters & Sci',
  'LAIS': 'Lat Amer & Iber',
  'LAWSO': 'Law and Society',
  'LING': 'Linguistics',
  'MATH': 'Mathematics',
  'MATRL': 'Materials',
  'MDVST': 'Medieval Stds',
  'ME': 'Mechanical Engr',
  'MILSC': 'Military Sci',
  'MUSIC': 'Music',
  'PHIL': 'Philosophy',
  'PHYS': 'Physics',
  'POLS': 'Political Sci',
  'PSY': 'Psy & Brain Sci',
  'RELST': 'Religious Stds',
  'RENST': 'Renaissance St',
  'SOC': 'Sociology',
  'SP&PT': 'Spanish & Port',
  'SPCH': 'Speech&Hear Sci',
  'STATS': 'Stats Appl Prob',
  'COMM': 'Communication',
  'ART': 'Art',
  'MAT': 'Media Arts & Te',
  'THTDA': 'Theater & Dance',
  'ERTSC': 'Earth Science',
  'CNCSP': 'Couns/Clin/Schl',
  'EALCS': 'E As Lng & Clt',
  'FEMST': 'Feminist Stds',
  'TMP': 'Tech Management',
  'DYNS': 'Dynamical Neuro',
  'WRIT': 'Writing Program',
  'ESM': 'Env. Sci. & Mgm',
  'EEMB': 'Ecol Ev Mar Bio',
  'MCDB': 'Mol Cel Dev Bio',
  'GLOBL': 'Global Studies',
  'MARSC': 'Marine Science',
  'NO': 'No Department',
  'BMSE': 'Bio Mol Sci Eng',
  'CLASS': 'Classics',
  'GRDIV': 'Graduate Div',
  'ESS': 'Exer Sport Stds',
  'BIOE': 'Biological Eng'
}